version: '3.3'
services:
  komga:
    image: gotson/komga
    container_name: komga
    volumes:
      - type: bind
        source: ./config
        target: /config
      - type: bind
        source: $HOME/Downloads/Manga
        target: /books
        read_only: true
    ports:
      - 8080:8080
    user: "1000:1000"
    environment:
      - HOGE=hoge
    restart: unless-stopped